import {StyleSheet} from 'react-native';

export const RegisterStyle = StyleSheet.create({
  modelCameraText: {
    color: '#FB3F39',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 16,
  },
  modelCameraTextCancel: {color: 'white', textAlign: 'center', fontSize: 16},
  modelCameraCancel: {
    width: '50%',
    height: 40,
    backgroundColor: '#FB3F39',
    borderColor: '#FB3F39',
    borderWidth: 1,
    borderRadius: 15,
    justifyContent: 'center',
    marginBottom: 10,
    alignSelf: 'center',
    marginTop: 10,
  },
  modelCameraBtn: {
    width: '50%',
    height: 40,
    backgroundColor: 'white',
    borderColor: '#FB3F39',
    borderWidth: 2,
    borderRadius: 15,
    justifyContent: 'center',
    marginBottom: 10,
    alignSelf: 'center',
    marginTop: 10,
  },
  modelView: {
    height: '30%',
    width: '100%',
    backgroundColor: 'white',
    borderTopRightRadius: 15,
    borderTopLeftRadius: 15,
    alignSelf: 'center',
    marginTop: 'auto',
    borderTopColor: 'red',
    borderTopWidth: 1,
  },
  IPcontainer: {
    width: '100%',
    height: 200,
    justifyContent: 'center',
  },
  IPcommandButton: {
    padding: 15,
    borderRadius: 10,
    backgroundColor: '#FF6347',
    alignItems: 'center',
    marginTop: 10,
  },
  IPheader: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#333333',
    paddingTop: 'auto',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  IPpanelHeader: {
    alignItems: 'center',
  },
  IPpanelHandle: {
    width: 40,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#00000040',
    marginBottom: 10,
  },
  IPpanelTitle: {
    fontSize: 27,
    height: 35,
  },
  IPpanelSubtitle: {
    fontSize: 14,
    color: 'gray',
    height: 30,
    marginBottom: 10,
  },
  IPpanelButton: {
    padding: 13,
    borderRadius: 10,
    backgroundColor: '#FF6347',
    alignItems: 'center',
    marginVertical: 7,
  },
  IPpanelButtonTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: 'white',
  },
  IPaction: {
    flexDirection: 'row',
    marginTop: 10,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f2f2f2',
    paddingBottom: 5,
  },
  IPactionError: {
    flexDirection: 'row',
    marginTop: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#FF0000',
    paddingBottom: 5,
  },
  IPTextInput: {
    flex: 1,
    marginTop: Platform.OS === 'ios' ? 0 : -12,
    paddingLeft: 10,
    color: '#05375a',
  },
  //
  circleView: {
    height: 40,
    alignSelf: 'center',
    flexDirection: 'row',
    marginTop: '4%',
  },
  circleBTN: {
    borderWidth: 1,
    borderColor: '#F06565',
    backgroundColor: '#F06565',
    alignItems: 'center',
    justifyContent: 'center',
    width: 30,
    height: 30,
    borderRadius: 50,
    marginTop: '-2%',
  },
  circleBTN02: {
    borderWidth: 1,
    borderColor: '#A6A6A6',
    backgroundColor: '#A6A6A6',
    alignItems: 'center',
    justifyContent: 'center',
    width: 30,
    height: 30,
    borderRadius: 50,
    marginTop: '-2%',
  },
  header: {
    width: '100%',
  },

  bottom: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    flex: 1,
    marginTop: 25,
  },

  forgetPass: {
    color: '#DC3030',
    fontWeight: 'bold',
    marginBottom: 10,
  },

  regisContainer: {
    marginTop: 15,
    justifyContent: 'center',
    flexDirection: 'row',
  },
  font15: {
    fontSize: 15,
  },

  regisTex: {
    color: '#02BAEC',
    fontWeight: 'bold',
  },
  textType: {
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    fontSize: 16,
    marginBottom: 11,
  },
  textName: {
    flexDirection: 'row',
    height: 40,
    borderWidth: 1,
    justifyContent: 'center',
  },
  imageCalendarView: {
    flexDirection: 'row',
    height: 40,
    marginBottom: 11,
  },
  imageIDView: {
    borderRadius: 10,
    borderColor: '#D9D9D9',
    borderWidth: 1,
    height: 220,
  },
  imageCalendar: {
    width: '100%',
    height: '100%',
    resizeMode: 'stretch',
    marginLeft: 'auto',
  },
  imageID: {
    width: 280,
    height: 190,
    resizeMode: 'contain',
    alignSelf: 'center',
    borderRadius: 5,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    backgroundColor: 'white',
    marginBottom: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#D9D9D9',
  },
  text: {
    color: 'white',
    fontSize: 15,
    textAlign: 'center',
  },
  containerAlert: {
    flex: 1,
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  buttonPopup: {
    backgroundColor: '#FB3F39',
    marginBottom: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#FB3F39',
    width: '60%',
    height: 40,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  buttonOKCancel: {color: 'white', textAlign: 'center'},
  dropdownContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#D9D9D9',
    width: '92%',
    marginLeft: '4%',
    marginTop: '5%',
  },
  dropdownStyle: {
    width: 300,
    height: 45,
    borderColor: 'blue',
    borderWidth: 1,
  },
  btnCheckbox: {
    flex: 1,
    flexDirection: 'row',
    marginTop: '3%',
    width: '80%',
  },

  register4_container: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    paddingTop: 50,
    backgroundColor: '#FFFFFF',
  },
  register4_textGeneral: {width: '90%', textAlign: 'center', fontSize: 18},
  register4_CaptchaContainer: {
    width: '100%',
    flexDirection: 'row',
    marginTop: 33,
    justifyContent: 'space-around',
  },
  register4_Captcha: {
    width: 40,
    height: 40,
    borderRadius: 5,
    borderColor: '#939393',
    borderWidth: 1,
    textAlign: 'center',
  },
});
